AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # SNS Topic for Budget Alerts
  # This topic will be used by AWS Budgets to send notifications when budget thresholds are exceeded
  TopicBudgetAlert:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: topic--budget-alert
      Tags:
        - Key: CostCenter
          Value: Financeiro
        - Key: Service
          Value: BudgetAlert
        - Key: Owner
          Value: OtavioKoike
  
  TopicBudgetAlertPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref TopicBudgetAlert
      PolicyDocument:
        Version: "2008-10-17"
        Id: "PolicyTopicBudgetAlert"
        Statement:
          - Sid: "AllowPublishByBudgets"
            Effect: Allow
            Principal:
              Service: budgets.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref TopicBudgetAlert
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub "${AWS::AccountId}"
          - Sid: "AllowSubscribe"
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - SNS:ListSubscriptionsByTopic
              - SNS:GetTopicAttributes
              - SNS:Subscribe
            Resource: !Ref TopicBudgetAlert
            Condition:
              StringEquals:
                AWS:SourceAccount: !Sub "${AWS::AccountId}"

  # Lambda Function for Budget Alerts
  # This function will be triggered by the SNS topic when budget thresholds are exceeded 
  LambdaBudgetAlertRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: role--budget-alert
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PolicyBudgetAlertLogs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambda--budget-alert:*
        - PolicyName: PolicyBudgetAlertSNS
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sns:Subscribe
                  - sns:ReceiveMessage
                Resource: !Ref TopicBudgetAlert
        - PolicyName: PolicyBudgetAlertCostExplorer
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                Resource: "*"
        - PolicyName: PolicyBudgetAlertResources
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StopInstances
                  - rds:DescribeDBInstances
                  - rds:StopDBInstance
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateContinuousBackups
                  - elasticache:DescribeCacheClusters
                  - elasticache:DeleteCacheCluster
                  - lambda:GetFunctionConfiguration
                  - lambda:UpdateFunctionConfiguration
                  - apigateway:GetRestApis
                  - apigateway:DeleteRestApi
                Resource: "*"
      Tags:
        - Key: CostCenter
          Value: Financeiro
        - Key: Service
          Value: BudgetAlert
        - Key: Owner
          Value: OtavioKoike

  LambdaBudgetAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda--budget-alert
      Handler: app.lambda_handler
      Runtime: python3.13
      Role: !GetAtt LambdaBudgetAlertRole.Arn
      CodeUri:
        Bucket: !Sub "${AWS::AccountId}--serverless-deployments"
        Key: "lambda_budget_alert.zip"
      Events:
        SNSBudgetAlert:
          Type: SNS
          Properties:
            Topic: !Ref TopicBudgetAlert
      Tags:
        CostCenter: Financeiro
        Service: BudgetAlert
        Owner: OtavioKoike

  LambdaBudgetAlertPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LambdaBudgetAlertFunction
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref TopicBudgetAlert

  LambdaBudgetAlertSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt LambdaBudgetAlertFunction.Arn
      TopicArn: !Ref TopicBudgetAlert
