AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LambdaBudgetAlertRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: role--budget-alert
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PolicyBudgetAlert
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sns:Subscribe
                  - sns:ReceiveMessage
                Resource: !Sub "arn:aws:sns:us-east-2:${AWS::AccountId}:topic--budget-alert"
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StopInstances
                  - rds:DescribeDBInstances
                  - rds:StopDBInstance
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateContinuousBackups
                  - elasticache:DescribeCacheClusters
                  - elasticache:DeleteCacheCluster
                  - lambda:GetFunctionConfiguration
                  - lambda:UpdateFunctionConfiguration
                  - apigateway:GetRestApis
                  - apigateway:DeleteRestApi
                Resource: "*"
      Tags:
        - Key: CostCenter
          Value: Financeiro
        - Key: Service
          Value: BudgetAlert
        - Key: Owner
          Value: OtavioKoike

  LambdaBudgetAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda--budget-alert
      Handler: app.lambda_handler
      Runtime: python3.13
      Role: !GetAtt LambdaBudgetAlertRole.Arn
      CodeUri:
        Bucket: !Sub "${AWS::AccountId}--serverless-deployments"
        Key: "lambda_budget_alert.zip"
      Events:
        SNSBudgetAlert:
          Type: SNS
          Properties:
            Topic: !Sub "arn:aws:sns:us-east-2:${AWS::AccountId}:topic--budget-alert"
        ScheduledExecution:
          Type: Schedule
          Properties:
            Schedule: "cron(0 6,14,22 * * ? *)"

  LambdaBudgetAlertPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LambdaBudgetAlertFunction
      Principal: 'sns.amazonaws.com'
      SourceArn: !Sub "arn:aws:sns:us-east-2:${AWS::AccountId}:topic--budget-alert"

  LambdaBudgetAlertSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt LambdaBudgetAlertFunction.Arn
      TopicArn: !Sub "arn:aws:sns:us-east-2:${AWS::AccountId}:topic--budget-alert"
